# Generated by Django 2.2.4 on 2021-02-13 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='CoffeeMachineProduct',
        ),
        migrations.CreateModel(
            name='CoffeePodProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.Category')),
                ('pack_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.PackSize')),
            ],
        ),
    ]
