# Generated by Django 2.2.4 on 2021-02-13 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_auto_20210213_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeePodFlavour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Vanilla', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='coffeepodproduct',
            name='flavor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coffee.CoffeePodFlavour'),
        ),
    ]
